### ISSUE TITLE
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by mrmrn** [yukiB/rnntest#1]
marn@marn-HP-Compaq-Elite-8300-SFF ~/c/p/5parameter> python3 simpleTFenn.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 866, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("inference/add:0", shape=(?, 80), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simpleTFenn.py", line 116, in <module>
    output_op, states_op, datas_op = inference(input_ph, istate_ph)
  File "simpleTFenn.py", line 52, in inference
    in4 = tf.split(0, length_of_sequences, in3)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1306, in split
    axis=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 5168, in _split
    "Split", split_dim=axis, value=value, num_split=num_split, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

**Comment by Rowing0914** [comment]
Hi, this is caused by the upgrade of Tensorflow.
When it evolves, a lot of files were moved to another directory, and some functions are overridden as well.
With regard to the arguments of split, in this repo's code, it looks like this
`tf.split(0, length_of_sequences, in3)`
but, this should be like this 
`tf.split(in3, length_of_sequences, 0)`

if you have any further question, please refer to here!
https://www.tensorflow.org/api_docs/python/tf/split
